# Script para verificação de consistência dos dados 
-- Verificar total de registros por tabela
SELECT 'CLIENTE' as tabela, COUNT(*) as total FROM CLIENTE
UNION ALL
SELECT 'CATEGORIA_RESTAURANTE', COUNT(*) FROM CATEGORIA_RESTAURANTE
UNION ALL
SELECT 'CEP_LOCALIDADE', COUNT(*) FROM CEP_LOCALIDADE
UNION ALL
SELECT 'ENTREGADOR', COUNT(*) FROM ENTREGADOR
UNION ALL
SELECT 'PROMOCAO', COUNT(*) FROM PROMOCAO
UNION ALL
SELECT 'ENDERECO', COUNT(*) FROM ENDERECO
UNION ALL
SELECT 'RESTAURANTE_NORMALIZADO', COUNT(*) FROM RESTAURANTE_NORMALIZADO
UNION ALL
SELECT 'PRODUTO', COUNT(*) FROM PRODUTO
UNION ALL
SELECT 'CLIENTE_PROMOCAO', COUNT(*) FROM CLIENTE_PROMOCAO
UNION ALL
SELECT 'PEDIDO', COUNT(*) FROM PEDIDO
UNION ALL
SELECT 'ITEM_PEDIDO', COUNT(*) FROM ITEM_PEDIDO
UNION ALL
SELECT 'PAGAMENTO', COUNT(*) FROM PAGAMENTO
UNION ALL
SELECT 'AVALIACAO_RESTAURANTE', COUNT(*) FROM AVALIACAO_RESTAURANTE
UNION ALL
SELECT 'AVALIACAO_ENTREGADOR', COUNT(*) FROM AVALIACAO_ENTREGADOR;

-- Verificar se todos os pedidos têm pagamento
SELECT p.numero_pedido, p.valor_total, pg.valor as valor_pagamento 
FROM PEDIDO p 
LEFT JOIN PAGAMENTO pg ON p.numero_pedido = pg.numero_pedido
WHERE pg.numero_pedido IS NULL;

-- Verificar se todos os pedidos têm itens
SELECT p.numero_pedido, COUNT(ip.codigo_produto) as qtd_itens
FROM PEDIDO p 
LEFT JOIN ITEM_PEDIDO ip ON p.numero_pedido = ip.numero_pedido
GROUP BY p.numero_pedido
HAVING qtd_itens = 0;